### ISSUE TITLE
Unable to mount my own configuration files.

### ISSUE THREAD

**Issue by thomascenni** [bitnami/bitnami-docker-couchdb#2]
**Description**

I want to modify the CouchDB configuration (enabling CORS, modifying timeouts, ...) and I am following the documentation available here:  
https://github.com/bitnami/bitnami-docker-couchdb#mounting-your-own-configuration-files
When I run the image with this command:

`docker run --name couchdb -v /Users/thomas/Desktop/couch:/opt/bitnami/couchdb/etc bitnami/couchdb:latest`

the server doesn't start.

**Steps to reproduce the issue:**

`docker run --name couchdb -v /Users/thomas/Desktop/couch:/opt/bitnami/couchdb/etc bitnami/couchdb:latest`

**Describe the results you received:**
couchdb 17:12:59.58 INFO  ==> ** Starting CouchDB setup **
couchdb 17:12:59.61 WARN  ==> You set the environment variable COUCHDB_PASSWORD=couchdb. This is the default value when bootstrapping CouchDB and should not be used in production environments.
couchdb 17:12:59.66 INFO  ==> Initializing CouchDB...
couchdb 17:12:59.67 WARN  ==> '/opt/bitnami/couchdb/etc/default.d/10-bitnami.ini' is not writable by the current user. Skipping modifications...
couchdb 17:12:59.68 WARN  ==> '/opt/bitnami/couchdb/etc/vm.args' is not writable by the current user. Skipping modifications...
couchdb 17:12:59.70 INFO  ==> Deploying CouchDB from scratch
couchdb 17:12:59.70 INFO  ==> Starting CouchDB in background...
timeout reached before the port went into state "inuse"

**Describe the results you expected:**

I expect the server to start allowing me to see archives in my under the directory created in my Desktop.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
MacOS 10.12.6

**Comment by dani8art** [comment]
Hi @thomascenni 

If you use `/opt/bitnami/couchdb/etc` you should override the entire configuration files, if you want to use just a custom.ini with some additional configuration please use `/opt/bitnami/couchdb/etc/local.d`. Could you try this?

```bash
$ docker run --rm -d --name couchdb -v $(pwd)/conf:/opt/bitnami/couchdb/etc/local.d bitnami/couchdb:latest
```

**Comment by thomascenni** [comment]
Thanks, it works perfectly!
