### ISSUE TITLE
Couchdb health check cannot be performed w/o valid user

### ISSUE THREAD

**Issue by ngspinu** [bitnami/bitnami-docker-couchdb#4]
Unless require_valid_user=false you can't ping the VSI to see if couch is alive.
Would be nice to have an endpoint running for healtchecks like: GET /_up

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-couchdb#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
